logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format:
        "%(asctime)s - %(levelname)s:
        [%(processName)s|%(name)s]:
        %(message)s"
  handlers:
    stream_handler:
      class: logging.StreamHandler
      formatter: simple
  loggers:
    '':
      handlers:
        - stream_handler
      level: INFO
